import pygame

pygame.init()
FPS = 60

WIDTH, HEIGHT = 1500, 1000
WINDOW = pygame.display.set_mode((WIDTH, HEIGHT))
pygame.display.set_caption("Blackjack")
pygame.display.set_icon(pygame.image.load("./assets/icon.png"))

# COLORS
DARKER_GREEN = (0, 100, 0)
BLUE = (0, 50, 255)
WHITE = (255, 255, 255)
RED = (255, 0, 0)
GREEN = (0, 255, 0)
BLACK = (0, 0, 0)


# Chips
chip_1 = pygame.image.load("./assets/chip_1.png")
chip_10 = pygame.image.load("./assets/chip_10.png")
chip_100 = pygame.image.load("./assets/chip_100.png")
chip_500 = pygame.image.load("./assets/chip_500.png")

# Background
title_background = pygame.transform.scale(pygame.image.load("./assets/title_background.png"), (WIDTH, HEIGHT))
background = pygame.transform.scale(pygame.image.load("./assets/blackjack_background.png"), (WIDTH, HEIGHT))

# Cards
cardback = pygame.image.load("./assets/cards/cardback.png")
clover_a = (pygame.image.load("./assets/cards/ac.png"), 11)
clover2 = (pygame.image.load("./assets/cards/2c.png"), 2)
clover3 = (pygame.image.load("./assets/cards/3c.png"), 3)
clover4 = (pygame.image.load("./assets/cards/4c.png"), 4)
clover5 = (pygame.image.load("./assets/cards/5c.png"), 5)
clover6 = (pygame.image.load("./assets/cards/6c.png"), 6)
clover7 = (pygame.image.load("./assets/cards/7c.png"), 7)
clover8 = (pygame.image.load("./assets/cards/8c.png"), 8)
clover9 = (pygame.image.load("./assets/cards/9c.png"), 9)
clover10 = (pygame.image.load("./assets/cards/10c.png"), 9)
clover_j = (pygame.image.load("./assets/cards/jc.png"), 10)
clover_k = (pygame.image.load("./assets/cards/kc.png"), 10)
clover_q = (pygame.image.load("./assets/cards/qc.png"), 10)
diamond_a = (pygame.image.load("./assets/cards/ad.png"), 11)
diamond_2 = (pygame.image.load("./assets/cards/2d.png"), 2)
diamond_3 = (pygame.image.load("./assets/cards/3d.png"), 3)
diamond_4 = (pygame.image.load("./assets/cards/4d.png"), 4)
diamond_5 = (pygame.image.load("./assets/cards/5d.png"), 5)
diamond_6 = (pygame.image.load("./assets/cards/6d.png"), 6)
diamond_7 = (pygame.image.load("./assets/cards/7d.png"), 7)
diamond_8 = (pygame.image.load("./assets/cards/8d.png"), 8)
diamond_9 = (pygame.image.load("./assets/cards/9d.png"), 9)
diamond_10 = (pygame.image.load("./assets/cards/10d.png"), 10)
diamond_j = (pygame.image.load("./assets/cards/jd.png"), 10)
diamond_k = (pygame.image.load("./assets/cards/kd.png"), 10)
diamond_q = (pygame.image.load("./assets/cards/qd.png"), 10)
heart_a = (pygame.image.load("./assets/cards/ah.png"), 11)
heart_2 = (pygame.image.load("./assets/cards/2h.png"), 2)
heart_3 = (pygame.image.load("./assets/cards/3h.png"), 3)
heart_4 = (pygame.image.load("./assets/cards/4h.png"), 4)
heart_5 = (pygame.image.load("./assets/cards/5h.png"), 5)
heart_6 = (pygame.image.load("./assets/cards/6h.png"), 6)
heart_7 = (pygame.image.load("./assets/cards/7h.png"), 7)
heart_8 = (pygame.image.load("./assets/cards/8h.png"), 8)
heart_9 = (pygame.image.load("./assets/cards/9h.png"), 9)
heart_10 = (pygame.image.load("./assets/cards/10h.png"), 10)
heart_j = (pygame.image.load("./assets/cards/jh.png"), 10)
heart_k = (pygame.image.load("./assets/cards/kh.png"), 10)
heart_q = (pygame.image.load("./assets/cards/qh.png"), 10)
spade_a = (pygame.image.load("./assets/cards/as.png"), 11)
spade_2 = (pygame.image.load("./assets/cards/2s.png"), 2)
spade_3 = (pygame.image.load("./assets/cards/3s.png"), 3)
spade_4 = (pygame.image.load("./assets/cards/4s.png"), 4)
spade_5 = (pygame.image.load("./assets/cards/5s.png"), 5)
spade_6 = (pygame.image.load("./assets/cards/6s.png"), 6)
spade_7 = (pygame.image.load("./assets/cards/7s.png"), 7)
spade_8 = (pygame.image.load("./assets/cards/8s.png"), 8)
spade_9 = (pygame.image.load("./assets/cards/9s.png"), 9)
spade_10 = (pygame.image.load("./assets/cards/10s.png"), 10)
spade_j = (pygame.image.load("./assets/cards/js.png"), 10)
spade_k = (pygame.image.load("./assets/cards/ks.png"), 10)
spade_q = (pygame.image.load("./assets/cards/qs.png"), 10)